### ISSUE TITLE
:bug: 이유는 모르겠지만 로컬에서 돌리다 보면 터저요

### ISSUE THREAD

**Issue by KKWANH** [PPiing/backend#191]
```
[Nest] 12756  - 2022. 08. 06. 오후 5:04:03   DEBUG [ChatroomsService] exec muteStopper

/Users/kimkwanho/Documents/Programming/42Seoul/42cursus/06_ft_transcendence/backend/src/error/TypeORMError.ts:7
        super(message);
        ^
TypeORMError: Empty criteria(s) are not allowed for the delete method.
    at new TypeORMError (/Users/kimkwanho/Documents/Programming/42Seoul/42cursus/06_ft_transcendence/backend/src/error/TypeORMError.ts:7:9)
    at EntityManager.delete (/Users/kimkwanho/Documents/Programming/42Seoul/42cursus/06_ft_transcendence/backend/src/entity-manager/EntityManager.ts:567:35)
    at ChatEventRepository.Repository.delete (/Users/kimkwanho/Documents/Programming/42Seoul/42cursus/06_ft_transcendence/backend/src/repository/Repository.ts:263:35)
    at ChatEventRepository.delChatEvent (/Users/kimkwanho/Documents/Programming/42Seoul/42cursus/06_ft_transcendence/backend/src/chatrooms/repository/chat-event.repository.ts:70:22)
    at /Users/kimkwanho/Documents/Programming/42Seoul/42cursus/06_ft_transcendence/backend/src/chatrooms/chatrooms.service.ts:85:68
    at Array.map (<anonymous>)
    at ChatroomsService.muteStopper (/Users/kimkwanho/Documents/Programming/42Seoul/42cursus/06_ft_transcendence/backend/src/chatrooms/chatrooms.service.ts:85:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ChatroomsService.onModuleInit (/Users/kimkwanho/Documents/Programming/42Seoul/42cursus/06_ft_transcendence/backend/src/chatrooms/chatrooms.service.ts:40:5)
    at async Promise.all (index 0)
```

**Comment by joohongpark** [comment]
해당 문제와 연관이 있어보이는 라이브러리를 제거하였는데 이후로도 계속 터진다면 다른 조치를 취해보겠습니다.

**Comment by KKWANH** [comment]
> 해당 문제와 연관이 있어보이는 라이브러리를 제거하였는데 이후로도 계속 터진다면 다른 조치를 취해보겠습니다.

계속 발생하는 것 같습니다.
무한 로딩 뜨다가 Timeout 뜨는 거랑 같은 에러인 것 같습니다.
프론트 쪽 문제인지 back 쪽 문제인지도 모르겠네요

**Comment by joohongpark** [comment]
https://github.com/PPiing/frontend/issues/269
